EXPECTED_TOP_FIVE_DIFFERENCES_ENDPOINT_RESPONSE = (
    """<!DOCTYPE html>\n\n<div class="result">\n    """
    """<img src=https://image.tmdb.org/t/p/original/n1sY9uAsQKOus91A4FtvN3JdHYH.jpg, style="height:100%">\n    """
    """<div class="result-text">\n        """
    """<div class="film-title">\n            """
    """Her\n        """
    """</div>\n        """
    """<div>\n            """
    """You gave it ★★★★. georgiebr97 gave it ★\n        """
    """</div>\n    """
    """</div>\n"""
    """</div>\n\n"""
    """<div class="result">\n    """
    """<img src=https://image.tmdb.org/t/p/original/fDUywEHwHh6nsLnVXAdPN9m4ZUG.jpg, style="height:100%">\n    """
    """<div class="result-text">\n        """
    """<div class="film-title">\n            """
    """The Wonderful Story Of Henry Sugar\n        """
    """</div>\n        """
    """<div>\n            """
    """You gave it ★★★★½. geminyxia gave it ★½\n        """
    """</div>\n    """
    """</div>\n"""
    """</div>\n\n"""
    """<div class="result">\n    """
    """<img src=https://image.tmdb.org/t/p/original/6XN1vxHc7kUSqNWtaQKN45J5x2v.jpg, style="height:100%">\n    """
    """<div class="result-text">\n        """
    """<div class="film-title">\n            """
    """Uncut Gems\n        """
    """</div>\n        """
    """<div>\n            """
    """You gave it ★★★★★. georgiebr97 gave it ★★½\n        """
    """</div>\n    </div>\n"""
    """</div>\n\n"""
    """<div class="result">\n    """
    """<img src=https://image.tmdb.org/t/p/original/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg, style="height:100%">\n    """
    """<div class="result-text">\n        """
    """<div class="film-title">\n            """
    """The Lord Of The Rings The Fellowship Of The Ring\n        """
    """</div>\n        """
    """<div>\n            """
    """You gave it ★★★★½. bethanyrosetta gave it ★★\n        """
    """</div>\n    """
    """</div>\n"""
    """</div>\n\n"""
    """<div class="result">\n    """
    """<img src=https://image.tmdb.org/t/p/original/kLcqyCqFYmMobD2POYASWMLfNPO.jpg, style="height:100%">\n    """
    """<div class="result-text">\n        """
    """<div class="film-title">\n            """
    """High Life 2018\n        """
    """</div>\n        """
    """<div>\n            """
    """You gave it ★★★★½. bethanyrosetta gave it ★★½\n        """
    """</div>\n    """
    """</div>\n"""
    """</div>"""
)